[package]
name = "rs-embedded-fish"
version = "0.1.0"
authors = ["Patrick Pelletier <code@funwithsoftware.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-slice-cast = "0.3.5"
embedded-graphics = "0.6.2"
rand = { version = "0.7.3", default-features = false }
rand_pcg = "0.2.1"
