[package]
name = "rs-embedded-fish"
version = "0.1.0"
authors = ["Patrick Pelletier <code@funwithsoftware.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
